version: '3'

services:
  reactor-demo:
    image: sooabia/reactor-demo:1.0
    restart: always
    ports:
     - '80:8080'
    links:
      - redis

  redis:
    image: redis 
    ports:
      - "6379:6379"
    volumes:
      - /redis:/data/redis
    restart: always
