---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  selector:
    matchLabels:
      app: redis
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis
        ports:
        - containerPort: 6379
---
apiVersion: apps/v1
kind: Deployment 
metadata: 
  name: reactor-demo 
spec: 
  selector: 
    matchLabels: 
      app: reactor-demo 
  replicas: 3
  template:
    metadata: 
      labels: 
        app: reactor-demo 
    spec: 
      containers: 
      - name: reactor-demo 
        image: sooabia/reactor-demo:1.0
        ports: 
        - containerPort: 8080
---  
kind: Service 
apiVersion: v1 
metadata: 
  name: spring-service 
spec: 
  selector: 
    app: reactor-demo 
  ports: 
  - protocol: TCP 
    port: 80 
    targetPort: 8080
  type: LoadBalancer
